// <auto-generated />
namespace OwinAuthentication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Owintest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Owintest));
        
        string IMigrationMetadata.Id
        {
            get { return "202111100120035_Owintest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
